### ISSUE TITLE
Configure default user with environment variables.

### ISSUE THREAD

**Issue by Nutellaeis** [obi12341/docker-pyload#12]
Would it be possible to configure the default user with environment variables like "PYLOAD_USER, PYLOAD_PASSWORD" ? At the moment I always end up doing a "docker exec...." and changing it from inside.

**Comment by diegoweb** [comment]
I'm having the same issue. All downloaded files are being written as ROOT in Docker Host.
Did you figure it out a way to fix this?
Do you have another repository available at docker with this fix?

Thanks!

**Comment by DaPutzy** [comment]
How did u manage to do that? I could not execute `python pyLoadCore.py -u` while pyLoad was running. And if i tried to quit pyLoad the docker container would instantly restart.

EDIT: nvm, i just tried it again and this time it worked flawlessly.

**Comment by obi12341** [comment]
see #15 and check if this resolves your issue

**Comment by DaPutzy** [comment]
IMHO it would still be nice to specify a different default user on container creation via ENVIRONMENT variables.

EDIT: i could create a pull request with that feature if you want? @obi12341

**Comment by obi12341** [comment]
yeah true and of course it is possible. Imho it is just not worth the effort. You should use volumes to store the user data and you can changed the password of the user just after creating. At this point you never have to change password again.
If you need this feature and want to develop it, feel free to create a PR :)

**Comment by DaPutzy** [comment]
Since `pyLoadCore.py -u` is interactive i tried to build a script with `pexpect`.
Even though everything looks perfect, it does not delete nor create users.

I tried everything i could and it didnt work, i paste it here in case someone wants to give it a try.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# encoding: utf-8

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

import pexpect
import sys
import os

user_name = os.environ.get('DEFAULT_USER', 'pyload');
user_pass = os.environ.get('DEFAULT_PASS', 'pyload');

c = pexpect.spawn('/usr/bin/env python pyLoadCore.py -u');
#c.logfile = sys.stdout
#c.delaybeforesend = 0.1

c.expect('\[1\]/2/3/4:\s');
c.sendline('2');

result = c.expect(['pyload', '\[1\]/2/3/4:\s']);

if result==0:
    #we found a user named pyload, lets delete him
    print('default user does exist. we delete him and create a new one.');

    #delete user pyload
    c.sendline('3');
    c.expect('Username');
    c.sendline('pyload');

    #create new user
    c.expect('\[1\]/2/3/4:\s');
    c.sendline('1');
    c.expect('Username\s\[User\]:\s');
    c.sendline(user_name);
    c.expect('Password:\s');
    c.sendline(user_pass);
    c.expect('Password\s\(again\):\s');
    c.sendline(user_pass);

    #user is created now, we exit
    c.expect('\[1\]/2/3/4:\s');
    print('new user was created. we exit.');
    c.sendline('4');

if result==1:
    #we did not find a user named pyload, lets exit
    print('default user does not exist. we exit.');
    c.sendline('4');

```
