### ISSUE TITLE
Change Username and Password ?

### ISSUE THREAD

**Issue by rahul-FT** [obi12341/docker-pyload#15]
Is it possible to change username and password without editing directly in db ?

**Comment by DaPutzy** [comment]
You can change the password under `/admin/`. AFAIK there is no way to change the default username.

There is a line displayed `To add user or change passwords use: python pyLoadCore.py -u` but i could not execute the command while pyload was running, and could not quit pyload without the docker container instantly restarting.

EDIT: nvm, i tried it again and it worked:

1. open a shell to your docker container (i.e. `docker exec -it <container name> /bin/bash`) see [here](http://phase2.github.io/devtools/common-tasks/ssh-into-a-container/) for help
2. switch dir do `/opt/pyload/`
3. execute `python pyLoadCore.py -u`

Everything else is self explanatory when u see it.

**Comment by obi12341** [comment]
thanks @DaPutzy for clarifying this. :+1: 
I close the issue now.
