### ISSUE TITLE
no further updates to "writl/pyload:latest "

### ISSUE THREAD

**Issue by menaceone** [obi12341/docker-pyload#17]
Hello,
during latest troubleshooting I noticed the last push to `writl/pyload` on dockerhub is 5 months old.
Is docker hub support suspended?

greetings

**Comment by obi12341** [comment]
hey, no it is not. looks like the "linked repository" feature of docker hub has not worked anymore. Have triggered a new build on hub. Thanks.

**Comment by menaceone** [comment]
I think the feature works fine. It's just, that the last commit to this repo here was also 5 months ago.
Thing is, we need a new image when there are new commits on the Pyload repository.

**Comment by Nutellaeis** [comment]
May I ask for a new build here? There were some recent commits in pyload that I would love to have.

**Comment by skyfrk** [comment]
@obi12341 May I also ask for a new build because of [this](https://github.com/pyload/pyload/issues/3283)?

**Comment by obi12341** [comment]
triggered a new build. This all will get fixed, when pyload releases a new stable release. Building from master will require to either pin commit or periodically build.

**Comment by sNiXx** [comment]
Nice, thank you @obi12341! Do you think there will be a new stable release anytime soon - if ever? It has been so many years and there is so little information that I don't see this happening anytime soon...
