### ISSUE TITLE
omv + docker + pyload 1080p merge problem

### ISSUE THREAD

**Issue by eSephiroth** [obi12341/docker-pyload#18]
I use omv + docker + pyload
When I set the Quality Setting to 1080p , pyload download the video and audio desperately. There are two file, one is xxx.video.mp4, the other is xxx.audio.webm. Can they merge to one file?
And I install ffmpeg in root command line. Is that something with the docker?

Python: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
-- | --
OS: | posix linux2 Linux 4.18.0-0.bpo.1-amd64 #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) x86_64
pyLoad version: | 0.4.9
Installation Folder: | /opt/pyload
Config Folder: | /opt/pyload/pyload-config
Download Folder: | /opt/pyload/Downloads
Free Space: | 5.46 TiB
Language: | en
Webinterface Port: | 8187
Remote Interface Port: | 7227

**Comment by obi12341** [comment]
This is not about pyload and omv support. Feel free to contact the pyload devs
