### ISSUE TITLE
ExtractArchive - SevenZip missing 

### ISSUE THREAD

**Issue by pyLoad-nvc** [obi12341/docker-pyload#29]
After the friendly support of a pyload developer:

[https://github.com/pyload/pyload/issues/3872](url)

Is there a way to add "SevenZip" to an update so that folders can be excluded after extracting a file (and not just individual files)? I mean this function: "Don't extract the following files:".

`DEBUG	ADDON ExtractArchive: Found HjSplit 0.02 | Found UnRar 5.50 | Found UnZip 2.7.17 | Found UnTar 2.7.17`

**Comment by GammaC0de** [comment]
unrar should be removed in favor of 7zip

**Comment by obi12341** [comment]
@GammaC0de ty, is #31 sufficient or do we need all p7zip packages like described [here](https://wiki.ubuntuusers.de/7z/)?
`p7zip p7zip-full p7zip-rar `

**Comment by GammaC0de** [comment]
p7zip-rar and p7zip should be included. As for p7zip-full, it probably should also be included but I'm not sure. Tests should be made to verify

**Comment by GammaC0de** [comment]
OK, my final answer is:
include `p7zip-full` and ` p7zip-rar`, not  `p7zip`.

**Comment by pyLoad-nvc** [comment]
@obi12341 sorry for bothering you but is there any progress on this?

**Comment by pyLoad-nvc** [comment]
Thanks alot! It works great!
