### ISSUE TITLE
Please add SSL-support

### ISSUE THREAD

**Issue by ghost** [obi12341/docker-pyload#7]
Support for HTTPS would be nice but module python-openssl is not available. The "builtin" server in pyload should also be changed in "threaded".

**Comment by obi12341** [comment]
Hello @raschix,
thanks for your contribution.
SSL is out of the scope for this image. If you want to have encrypted Webfrontend, take a look at https://github.com/jwilder/nginx-proxy so you can use a nginx as a reverse proxy before your pyload. This is much safer, than having redundant ssl config in every container image.

**Comment by ghost** [comment]
Ok, thanks for the hint. I will look in this.
