### ISSUE TITLE
Webinterface not working

### ISSUE THREAD

**Issue by koarlmichael** [obi12341/docker-pyload#9]
Dockerimage: writl/pyload:latest
Webinterface not working:

**Critical error while processing request: /login**

**Comment by MangaValk** [comment]
same here -> __Critical error while processing request: /login__

**Comment by Bohrfutter** [comment]
same problem here: Critical error while processing request: /login

**Comment by obi12341** [comment]
They renamed the default template to classic. If you have existing pyload-config, please change this file as described in the commit. Thanks for reporting 👍
